### ISSUE TITLE
Astropy Unit Issue in Google Colab

### ISSUE THREAD

**Issue by vcatlett** [GreenBankObservatory/dysh#70] opened 2023-08-23 18:51 UTC
In Google Colab, calling GBTFITSLoad() before astropy.coordinates.EarthLocation() causes the EarthLocation call to fail. Both behave as expected when the initial order is reversed. See the 2023-08-16 meeting notes for a link to the Colab notebook. Here is the error that is produced:
```
>>> sdf = GBTFITSLoad("TGBT23A_609_11.raw.vegas.A.fits")
>>> gbt = EarthLocation.of_site("GBT")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/astropy/units/format/generic.py in _do_parse(cls, s, debug)
    586             # is just a single unit name
--> 587             return cls._parse_unit(s, detailed_exception=False)
    588         except ValueError as e:
17 frames
ValueError: 
During handling of the above exception, another exception occurred:
ValueError                                Traceback (most recent call last)
ValueError: meter is not a valid unit. 
During handling of the above exception, another exception occurred:
ValueError                                Traceback (most recent call last)
ValueError: At col 0, meter is not a valid unit. 
During handling of the above exception, another exception occurred:
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/astropy/units/core.py in __call__(self, s, represents, format, namespace, doc, parse_strict)
   2119                     )
   2120                     if parse_strict == "raise":
-> 2121                         raise ValueError(msg)
   2122                     elif parse_strict == "warn":
   2123                         warnings.warn(msg, UnitsWarning)
ValueError: 'meter' did not parse as unit: At col 0, meter is not a valid unit.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
```

I suspect that this is a consequence of the astropy unit warnings that come from SDFITSLoad() and GBTFITSLoad() calls:
```
WARNING: UnitsWarning: 'mmHg' did not parse as fits unit: At col 0, Unit 'mmHg' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING:astropy:UnitsWarning: 'mmHg' did not parse as fits unit: At col 0, Unit 'mmHg' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
WARNING: UnitsWarning: 'UTC' did not parse as fits unit: At col 0, Unit 'UTC' not supported by the FITS standard. Did you mean TC, uC or uT? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING:astropy:UnitsWarning: 'UTC' did not parse as fits unit: At col 0, Unit 'UTC' not supported by the FITS standard. Did you mean TC, uC or uT? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
```

**Comment by mpound** [comment] 2023-08-23 19:03
See also issue #42

**Comment by astrofle** [comment] 2023-11-16 18:41
This is still not working even after the fix to Issue #42. I will close this, as we now have a working binder for the example notebooks. 

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/astrofle/dysh-tutorials/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252FGreenBankObservatory%252Fdysh%26urlpath%3Dlab%252Ftree%252Fdysh%252Fnotebooks%252Fexamples%26branch%3Dmultifits)

**Closed by astrofle** 2023-11-16 18:41 UTC

**Comment by mpound** [comment] 2023-12-20 15:52
I have independently "discovered" this issue when working on Doppler shift.  The problem is the cds.enable() line in *FITSLoad.py.   This line was added in order to recognize mmHg as a unit. However, as noted (buried!) in the astropy documentation, cds.enable() will _disable_ default astropy units!  https://docs.astropy.org/en/stable/api/astropy.units.cds.enable.html#astropy.units.cds.enable

So we need a new solution for mmHg.  I am removing that line from *FITSLoad.py

**Comment by tchamberlin** [comment] 2023-12-20 16:38
I'm not sure if this avoids this issue or not, but their suggestion is to use a context manager instead of enabling this globally, e.g.

```py
with cds.enable():  # to get mmHg
    self._compute_proc()
```

Or if we need to use the unit explicitly anywhere then just using an explicit reference to `astropy.units.cds.mmHg`
