### ISSUE TITLE
implement weights in spectral averaging

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#13] opened 2023-06-20 19:29 UTC
need to implement weighting as in requirements document.

**Comment by astrofle** [comment] 2023-06-20 20:57
Here's an example of how the weights could work: [https://github.com/GreenBankObservatory/dysh/blob/psalas_debug/notebooks/compare_ps_with_weights.ipynb](https://github.com/GreenBankObservatory/dysh/blob/psalas_debug/notebooks/compare_ps_with_weights.ipynb)

It does not completely account for the differences we see between GBTIDL and Dysh. I'll keep looking to understand that difference.

**Comment by mpound** [comment] 2023-06-21 21:03
@teuben Can you comment on the level of differences you saw between GBTIDL and gbtoy for calibrated PS data?  And did you use weights in averaging?

**Comment by astrofle** [comment] 2023-06-27 17:11
The difference we see is not due to the weights as confirmed by Issue #28

**Comment by mpound** [comment] 2023-07-11 21:36
tsys and equal weighting done.  User-defined weights not yet implemented (but it is not hard)

**Comment by astrofle** [comment] 2023-07-17 14:47
I'm still getting differences when using the default arguments.
```
from dysh.fits.gbtfitsload import GBTFITSLoad
sdf_file = "/home/dysh/example_data/onoff-L/data/TGBT21A_501_11.raw.vegas.fits"
sdf = GBTFITSLoad(sdf_file)
psscan = sdf.getps(152)
psscan.calibrate()
psscan_tavg = psscan.timeaverage()

hdu = fits.open("/home/dysh/example_data/onoff-L/outputs/TGBT21A_501_11_getps_152_ifnum_0_plnum_0.fits")
data = hdu[1].data["DATA"]

np.nanmean(data[0] - psscan_tavg.flux.value)
   2.7357704e-08
np.nanmedian(data[0] - psscan_tavg.flux.value)
   2.9802322e-08
# The above should be zero.
```

**Comment by astrofle** [comment] 2023-07-18 00:16
`GBTIDL` uses floats to store the system temperature of a data container, but the computation of `dcmeantsys` uses doubles. After changing the data type of the `GBTIDL` accumulator to `double`, and also the data types used in `dysh.spectra.core.dcmeantsys` to `np.longdouble`, the system temperatures agree to 1e-15.
The next problem is that `dysh` losses precision when storing the `EXPOSURE` and `CDELT1` columns.
I have no energy to fix that now, but please go ahead if you can....

**Comment by mpound** [comment] 2023-07-18 13:49
EXPOSURE and CDELT are stored as np.float64, which is the equivalent to the '1D' format in SDFITS,  and `tsys_weight` is also computed as np.float64. Can you be more specific about where the precision is lost?
```
print(p.index(0)["EXPOSURE"].dtype, p.index(0)["CDELT1"].dtype)
tps = p.gettp(scan=152,sig=None,cal=None,bintable=0,ifnum=0,plnum=1)
print(tps._tsys_weight.dtype,tps.exposure.dtype,tps.delta_freq.dtype)
```
  float64 float64
  TPSCAN nrows = 302
  float64 float64 float64`

**Comment by astrofle** [comment] 2023-07-18 14:05
My bad, it is not the types of the variables, rather how the exposure is being calculated:
```
# dysh was doing:
exp_ref = 0.5*(exp_ref_on + exp_ref_off)
exp_sig = 0.5*(exp_sig_on + exp_sig_off)
exposure = 0.5*(exp_ref + exp_sig)
# GBTIDL does:
exp_ref = (exp_ref_on + exp_ref_off)
exp_sig = (exp_sig_on + exp_sig_off)
nsmooth = 1. # In case we start smoothing the reference spectra.
exposure = exp_sig*exp_ref*nsmooth/(exp_sig+exp_ref*nsmooth)
```
I pushed this change to `release-0.1.0` (I did not notice I was working there instead of in my branch...)

**Comment by astrofle** [comment] 2023-07-18 14:43
After  07f95d9 the weights agree. Closing this for now.

**Closed by astrofle** 2023-07-18 14:43 UTC
Labels: enhancement

**Comment by mpound** [comment] 2023-07-18 15:20
I changed this slightly to accomodate if weights are input as astropy.unit.Quantity.  Still passes pytest.

**Comment by teuben** [comment] 2024-04-16 21:27
the documentation in tsys_weight() says nothing about a longdouble, which is returned here.   It still makes NO sense to me (not having read this thread) that we NEED longdouble anywhere in dysh.  But at least there  should be some wording in that function on why we need longdouble, or refer to this issue.

**Comment by astrofle** [comment] 2024-04-17 02:36
Agree, we do not need long doubles for computing the weights. It was leftover from trying to figure out why the results of `GBTIDL` and `dysh` did not agree (it was a difference in how things are computed, not the precision). Feel free to change it to `float64` precision.

**Comment by mpound** [comment] 2024-04-17 13:31
I'll make the change.
