### ISSUE TITLE
Multiple flag rules not working

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#429] opened 2024-11-22 18:20 UTC
**Describe the bug**
I wanted to flag data using multiple rules, but only the last one seems to work.

**How to Reproduce**
```Python
import matplotlib.pyplot as plt
from pathlib import Path
from dysh.util.download import from_url
from dysh.fits.gbtfitsload import GBTFITSLoad

url = "http://www.gb.nrao.edu/dysh/example_data/rfi-L/data/AGBT17A_404_01.raw.vegas/AGBT17A_404_01.raw.vegas.A.fits"
savepath = Path.cwd() / "data"
filename = from_url(url, savepath)

sdfits = GBTFITSLoad(filename)

sdfits.flags.clear()
sdfits.flag(scan=20, 
            channel=[[2300,4096]], 
            intnum=[i for i in range(43,52)])
sdfits.flag_channel([[0,327],[4096-327,4096]])
sdfits.flags.show()

pssb = sdfits.getps(scan=19, plnum=0, apply_flags=True)

plt.figure(dpi=70)
plt.imshow(pssb[0]._calibrated, aspect="auto")
```

<img width="377" alt="Screenshot 2024-11-22 at 1 18 13 PM" src="https://github.com/user-attachments/assets/fa87cb34-9cf1-4900-acd7-c05d9bbeb95f">

As the Figure shows, only the edge channels are flagged, but it should also have flagged the range between 2300 and 4096 (blue region in the Figure).

**Environment**
- Dysh version 0.4.0a
- Python version 3.10
- OS

**Comment by mpound** [comment] 2024-11-26 17:10
This example fails because there is no scan 19 and 20 in the data (wrong data file?).  However, if I use scans 51 and 52, I see the same incorrect behavior.

```
import matplotlib.pyplot as plt
from pathlib import Path
from dysh.util.download import from_url
from dysh.fits.gbtfitsload import GBTFITSLoad

url = "http://www.gb.nrao.edu/dysh/example_data/rfi-L/data/AGBT17A_404_01.raw.vegas/AGBT17A_404_01.raw.vegas.A.fits"
savepath = Path.cwd() / "data"
filename = from_url(url, savepath)

sdfits = GBTFITSLoad(filename)
sdfits.summary()
   SCAN   OBJECT VELOCITY   PROC  ...  # INT # FEED     AZIMUTH   ELEVATIO
0    51  NGC5291   4386.0  OnOff  ...     11      1  198.343112   18.64274
1    52  NGC5291   4386.0  OnOff  ...     11      1  198.930571  18.787219
2    53  NGC5291   4386.0  OnOff  ...     11      1  199.330491  18.356075
3    54  NGC5291   4386.0  OnOff  ...     11      1  199.915725  18.492742
4    55  NGC5291   4386.0  OnOff  ...     11      1  200.304237  18.057533
5    56  NGC5291   4386.0  OnOff  ...     11      1  200.890603  18.186034
6    57  NGC5291   4386.0  OnOff  ...     11      1  202.327548  17.385267
7    58  NGC5291   4386.0  OnOff  ...     11      1  202.919161  17.494902
sdfits.clear_flags()
sdfits.flag(scan=51,channel=[[2300,4096]],intnum=[i for i in range(0,10)])
sdfits.flags.show()
 ID    TAG    SCAN         INTNUM             CHAN     # SELECTED
--- --------- ---- --------------------- ------------- ----------
  0 f4a970659   51 [0,1,2,3,4,5,6,7,8,9] [[2300,4096]]         40
sdfits.flag_channel([[0,327],[4096-327,4096]])

sdfits.flags.show()
 ID    TAG    SCAN         INTNUM                 CHAN         # SELECTED
--- --------- ---- --------------------- --------------------- ----------
  0 f4a970659   51 [0,1,2,3,4,5,6,7,8,9]         [[2300,4096]]         40
  1 35d755b90                            [[0,327],[3769,4096]]        352

pssb = sdfits.getps(scan=19, plnum=0, apply_flags=True)
plt.figure(dpi=70)
plt.imshow(pssb[0]._calibrated, aspect="auto")
```
![dysh429](https://github.com/user-attachments/assets/e85d319e-1e97-43bc-adfd-2dd39c7c4b85)

A simple test shows that the last flag overwrites the others:
```
sdfits.flag(scan=51,channel=[[2300,4096]],intnum=[i for i in range(0,10)])
sdfits.apply_flags()
np.where(sdfits._sdf[0]._flagmask[0])

(array([ 0,  0,  0, ..., 39, 39, 39]),
 array([2300, 2301, 2302, ..., 4094, 4095, 4096]))

sdfits.flag_channel([[0,327],[4096-327,4096]])
sdfits.apply_flags()
np.where(sdfits._sdf[0]._flagmask[0])

(array([  0,   0,   0, ..., 351, 351, 351]),
 array([   0,    1,    2, ..., 4094, 4095, 4096]))
```
(this would be a good regression test)

**Comment by mpound** [comment] 2024-11-26 20:07
This is now fixed by commit [796ffa](https://github.com/GreenBankObservatory/dysh/commit/796ffa51721cd6085f12558cba6ae5f0ab5a4e8c) .  Here is the plot of all channel flags after the fix.
```
plt.imshow(sdfits._sdf[0]._flagmask[0]*1,aspect='auto')
```
<img width="375" alt="dysh429fixed" src="https://github.com/user-attachments/assets/5f7ff33f-e48a-482b-a3f2-3ced0a2ef95d">

I also added a regression test.

**Closed by mpound** 2024-11-26 20:07 UTC
Labels: bug
