### ISSUE TITLE
Baseline exclusion range

### ISSUE THREAD

**Issue by leemundy** [GreenBankObservatory/dysh#6] opened 2023-06-19 16:00 UTC
If you make the exclusion range larger than the range of actual channels, baseline
executes without error but does not warn about being out of range and gives an incorrect
answer:
fig,ax=plt.subplots()
ax.plot(s2.spectral_axis,s2.flux)
s2.baseline(1,exclude=[350,6500],remove=True)
ax.plot(s2.spectral_axis,s2._baseline_model(s2.spectral_axis),color='r')
plt.show()

 
(my example plot does not upload properly by cut and paste or dropping)
![image](https://github.com/GreenBankObservatory/dysh/assets/28005518/dbab5099-ef0a-4e8b-8064-c9ef42bf53fa)

**Comment by mpound** [comment] 2023-06-19 16:49
Do you happen to still have these specific Y values that you can post here?  I have an example where exclude>range works fine, but for different randomly generated noise.  So I'm wondering if your case isn't just an unfortunate noise pattern.   Or you can try this a few times regenerating the y values each time and see how often it occurs.

**Comment by teuben** [comment] 2023-06-19 16:51
do we not use a fixed seed for the "random" noise examples? if not, we should.

**Comment by leemundy** [comment] 2023-06-19 17:03
the full code is

npts = 1000
x = np.arange(npts)
y2 = 1.0+np.random.rand(npts)+500*norm(loc=npts/2,scale=50).pdf(x)
s2 =
Spectrum(flux=y2*u.K,spectral_axis=x*u.um,velocity_convention='doppler_radio',radial_velocity=25*u.Unit('km/s'))

fig,ax=plt.subplots()
ax.plot(s2.spectral_axis,s2.flux)
s2.baseline(1,exclude=[350,6500],remove=True)
ax.plot(s2.spectral_axis,s2._baseline_model(s2.spectral_axis),color='r')
plt.show()

I tried 3 times and all three have weird fits.

Lee

**Comment by leemundy** [comment] 2023-06-19 17:04
I disagree. I think that the default should be new random noise each time.

**Comment by teuben** [comment] 2023-06-19 17:08
i guess it depends on the goal of the example.     for regression you want it reproducible.

**Comment by mpound** [comment] 2023-06-19 17:27
I believe this is a case of 'unfortunate random data'.    I ran Lee's snippet a few times to get a clearly "egregious" answer.  Then I took just the first 300 channels and fit only them.   The baseline model polynomial is essentially identical.
 

y3=y2.copy()[0:300]
x3=x[0:300]
s3=Spectrum(flux=y3*u.K,spectral_axis=x3*u.um,velocity_convention='doppler_radio',radial_velocity=25*u.Unit('km/s'))
fig,ax=plt.subplots()
ax.plot(s3.spectral_axis,s3.flux)
s3.baseline(1,remove=True)
ax.plot(s3.spectral_axis,s3._baseline_model(s3.spectral_axis),color='r')
print(s2.baseline_model,"\n",s3.baseline_model)

Model: Polynomial1D
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Degree: 1
Parameters:
           c0                c1         
           K               K / um       
    --------------- --------------------
    1.5003172599342 7.37958547768679e-05 
Model: Polynomial1D
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Degree: 1
Parameters:
            c0                   c1          
            K                  K / um        
    ------------------ ----------------------
    1.4918967647908639 0.00014993853600919237

![issue6](https://github.com/GreenBankObservatory/dysh/assets/22331890/9136da3f-c0ca-47af-84f5-766e0b0cacaa)

**Comment by leemundy** [comment] 2023-06-19 17:35
So the answer is to send the user an error warning and reset to the max
allowed?
Silence seems to me to be the wrong answer.

Lee

**Comment by mpound** [comment] 2023-06-19 17:43
Yes,warn and reset seems like the desired behavior.

**Comment by mpound** [comment] 2023-06-21 18:53
I'm not sure that reset is the desired behavior.   Might be bad precedent to "fix" user inputs to what we think they wanted.  Better to Warn and let them fix themselves if they meant something else.

**Comment by astrofle** [comment] 2023-07-13 13:08
This seems to be working now, even if the exclude region has units. I'll close it for now, but please let me know if there's still something that needs to be added.

**Closed by astrofle** 2023-07-13 13:08 UTC
Labels: Done
